version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  celery-worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    env_file:
      - .env
    restart: always

  celery-beat:
    build: .
    command: celery -A celery_app beat --loglevel=info
    env_file:
      - .env
    restart: always

  # Local Databases are optional and commented out since Cloud services (Neon, Atlas, Upstash) are being used.
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: finsight
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"

  # mongo:
  #   image: mongo:7
  #   ports:
  #     - "27017:27017"

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
